invoice.py, process_invoices.py
Implements [SYS-1021](https://jira.library.ucla.edu/browse/SYS-1021)
This PR changes the Alma -> PAC invoice processing program.  Instead of rejecting some invoices based on the first characters in the invoice number, these invoices will be rejected based on the value in the invoice reference number field.
That specific change is just a [few lines in `invoice.py`](https://github.com/UCLALibrary/alma-scripts/compare/SYS-1021/exclude_by_ref_num?expand=1#diff-f04a3d192757628e26e79557236e72ad61c8ef7f287039e355d332642531ef30R59-R61).
The rest of the changes in this PR are from reformatting by Black.
=> SYS-1021: Exclude invoice by reference number

alma_api_client.py, get_vendor_data.py
Implements [ALMA-129](https://jira.library.ucla.edu/browse/ALMA-129).
This PR adds a script which outputs a CSV file of basic contact info for active vendors where we have a campus financial code (VCK) in our records.  This was needed for a campus project and probably is a one-time script.
It uses Alma `vendors` API to quickly retrieve the codes for active vendors.  Unfortunately, that API can't search / filter by presence of data in `financial_sys_code`, so the script must retrieve full data for each active vendor via the `vendors/{{vendor_code}}` API.  The main contact person, and main email address (no relation in the data...) is captured from each vendor, where available.
Finally, it writes data for each active vendor with a VCK to a CSV file.
=> ALMA-129: Add script to get basic vendor contact data

alma_api_client.py, create_items.py, get_analytics_report.py, get_vendor_data.py, process_invoices.py
Part of [SYS-1060](https://jira.library.ucla.edu/browse/SYS-1060).
Renames class from `Alma_Api_Client` to `AlmaAPIClient` to comply with [PEP 8 class naming convention](https://peps.python.org/pep-0008/#class-names).
Updates all programs using this class accordingly.
=> SYS-1060: Rename API class to match PEP standards

export_requests_to_caia.py
Python 3.8 requires explicit import of `typing.Type`, instead of generic `type[]` hinting.
Also fixes bug where `alma_client` was not passed to `run_job()`.
=> SYS-1067: Downgrade type hinting for python 3.8, fix bug

alma_api_client.py
Implements [SYS-1062](https://jira.library.ucla.edu/browse/SYS-1062)
Adds a simple method to get a single bib record. Works with or without optional query string parameters (view = full, brief, local_fields; expand = p_avail, e_avail, d_avail, requests).
=> SYS-1062: Add API method to retrieve specific Alma bib record

alma_api_client.py
Implements [SYS-1063](https://jira.library.ucla.edu/browse/SYS-1063).  Includes code from both @ztucker4 and @akohler .
This PR implements an `update_bib()` API method for updating Alma bib records.  This required some internal changes to the class:
* Request headers are now format-specific, depending on `json` (the default) or `xml`
* Internal request handlers (`_call_get_api()`, etc.) are now nominally format-aware
* POST and DELETE requests are currently used only by JSON APIs
* PUT requests are currently used only by XML-only APIs
* XML response data from XML-only APIs is returned as `bytes` data in the method's `dict["content"]` return value.
```
>>> api_data = client.get_bib(mms_id)
>>> type(api_data["content"])
<class 'bytes'>
```
None of the class's existing public method …
=> SYS-1063: Add API method to update Alma bib records

alma_marc.py
Relates to [SYS-1074](https://jira.library.ucla.edu/browse/SYS-1074)
This PR implements two new functions useful in converting between MARCXML usable by pymarc and Alma Bib XML objects. `get_MARCXML_from_bib` retrieves the record MARCXML from an Alma Bib, `and update_alma_bib_xml` inserts a MARCXML record (presumably updated by pymarc) into an existing Alma Bib record.
There is no function converting directly from MARCXML to an Alma Bib, as the Bibs contain extra metadata that cannot be extrapolated from the MARC record. There is also no function converting a \<collection> object as written by pymarc to a \<record> object, as this is more easily accomplished with pymarc. Assuming `bib_record` is a pymarc Record, the below will give the desired \<record> XML:
```
single_record = …
```
=> SYS-1074: Convert between Alma Bib XML and MARCXML

get_alma_invoice_errors.py, get_alma_invoice_errors.sh
This PR adds:
* `get_alma_invoice_errors.py`: Python script to retrieve daily invoice error file from UCLA PAC SFTP server
* `get_alma_invoice_errors.sh`: Shell script which runs the Python script, shows contents, and is more suitable for cron usage
=> SYS-1112: Shell and python scripts to get Alma/PAC invoice error files

invoice.py, process_invoices.py
Implements [ALMA-147](https://jira.library.ucla.edu/browse/ALMA-147).
This fixes a problem where "normal" taxable discounts were being reported to PAC as exempt from taxation.  "Normal" discounts are those which are not associated with special / partial tax rates, which do need to remain exempt.
Also cleans up a few minor problems reported by vscode and updates incorrect / incomplete comments.
=> ALMA-147: Fix discount / credit handling

add_CAAS_holdings_note.py, alma_api_client.py
Implements [ALMA-128](https://jira.library.ucla.edu/browse/ALMA-128)
Adds two new functions to the Alma API client to support holdings records GET and PUT, and uses these in a script to add an 852 $z note on CAAS holdings.
The Analytics Report data is limited to the relevant library's holdings (confirmed via another report to never contain 852 $z), so the script simply inserts this subfield on all records. Tested in Sandbox on one holdings record, not yet tested with report integration in Production.
=> ALMA-128: Add holdings display note for CAAS

invoice.py
Implements [SYS-1343](https://jira.library.ucla.edu/browse/SYS-1343).
This PR removes the special regex used to identify Procard invoices.  From now on, they'll be identified by `PCARD` in the invoice reference number field, similar to most other Alma invoices which should not go to PAC.
=> SYS-1343: Change Procard invoice handling

patrons/geffen_loader.py
Fix for issue where data from campus is missing leading zeroes from UCLA UID.
=> SYS-1446: Left-pad short Geffen UID with zero

.gitignore, marc/make_west_analysis.py
Implements [SYS-1460](https://uclalibrary.atlassian.net/browse/SYS-1460).
This PR adds a Python script which prepares exported MARC records for upload to CDL for their WEST unarchived holdings analysis.  UCLA documentation: https://uclalibrary.atlassian.net/wiki/x/RwGCCg
[SYS-1460]: https://uclalibrary.atlassian.net/browse/SYS-1460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SYS-1460: Add Python script to process WEST unarchived holdings analysis records

add_bib_ebookplates.py, tests/data/sample_SPAC_mappings.csv, tests/test_add_bib_ebookplates.py, tests/test_update_bookplates_one_time.py, update_bookplates_one_time.py
Implements [SYS-1552](https://uclalibrary.atlassian.net/browse/SYS-1552)
This PR has two parts:
1. A small change to `add_bib_ebookplates.py` to remove a check that mapping SPAC codes did not change the length of the report. In real data, multiple fund codes can map to the same SPAC (and SPACs can map to multiple fund codes). In this case, any record associated with one of these fund codes should get all relevant bookplates applied. A new test is added for this (`test_get_report_ebookplates_multiple_spacs_single_fund`), and the test mapping file is updated to support it.
2. A new script, `update_bookplates_one_time.py`. This is intended for one-time use to update all existing bibs with 966 fields that need SPAC Name or URL changes. This is done with a new Alma Analytics report available …
=> SYS-1552: Add one-time bookplate update script, and remove report length check in add_bib_ebookplates.py

add_bib_ebookplates.py, update_bookplates_one_time.py
Implements [SYS-1554](https://uclalibrary.atlassian.net/browse/SYS-1554)
Several logging-related changes to `add_bib_ebookplates.py` and `update_bookplates_one_time.py`:
* Log level is now set with the command line argument `--log-level`, with possible values `"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"`. `INFO` is default.
* Logs from `urllib3` with lower priority than `WARNING` are now suppressed.
* All print statements have been changed to logs at the `INFO` level.
* Report index is now logged every 1% of records for easier rerunning in production.
* The optional `--start-index` argument is now supported in `add_bib_ebookplates.py`.
[SYS-1554]: https://uclalibrary.atlassian.net/browse/SYS-1554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
=> SYS-1554: fix logging in bookplate update scripts

remove_bookplates_one_time.py
Implements [SYS-1567](https://uclalibrary.atlassian.net/browse/SYS-1567)
After our project to add bookplate information into bib records to make them visible in Primo, we want to clean up old bookplates information in holdings records. In particular, this script is intended to delete the following "bookplates" fields from holdings records:
1. 856 fields that contain the string "Bookplate" in $3
2. 966 fields that _do not_ contain one of the FTVA SPACs to preserve (lines 97-147 in the script).
This script relies on two analytics reports, one for 856s and one for 966s. These reports do some basic filtering to check if the "Bookplate" string or the SPACs (respectively) are present anywhere in the field. The script confirms the removal conditions in the specific subfields in …
=> SYS-1567: Delete bookplates from holdings

remove_bookplates_one_time.py
Implements [SYS-1718](https://uclalibrary.atlassian.net/browse/SYS-1718)
Uses the `retry` package to retry failed calls when retrieving and updating Alma holdings records. Calls are tried up to three times, with a 20s delay and 2x backoff.
Exceptions are now handled for these calls if the retries do not work. Holdings resulting in exceptions are logged with Error messages in the log file, and are also written to a new output file (`errored_holdings_{datetime}.json`). This new output file can be used together with the new optional command-line argument `--local-report-data-path` to rerun only the errored holdings.
Log files now also include a timestamp in the filename. Logging is also updated to show the correct cumulative report index (see line 60).
To support these changes, `retry`, …
=> SYS-1718: handle exceptions in remove bookplates script

process_invoices.py
Fixes [SYS-1819](https://uclalibrary.atlassian.net/browse/SYS-1819).
Starting 5/2/2025, the value of the description field changed for the Alma job which exports our invoices.  This does not seem to be available via the Alma UI, and I don't know why it changed.  Since we use the description to identify the right job to run, this broke our export script.
I updated the description in code.
[SYS-1819]: https://uclalibrary.atlassian.net/browse/SYS-1819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SYS-1819: Update invoice job name

remove_bookplates_one_time.py
Implements [SYS-2021](https://uclalibrary.atlassian.net/browse/SYS-2021)
This PR updates the `remove_bookplates_one_time.py` script to use our new Alma API client package, and to bring the script in line with our current best-practices. The core functionality of the script remains the same: checking Alma holding records for bookplate information in certain sub-field, then removing that info as necessary.
Logging is refactored to use a helper method and to output to a `logs` sub-directory in the project folder. Loading of API keys is also refactored to use a TOML config file, which I'll send separately. Input data with `mms_id` and `holding_id` can be provided via a CSV Alma report file now, in addition to the JSON format originally supported. I will also send this data file separately. …
=> SYS-2021: Update `remove_bookplates_one_time.py` to use new `AlmaAPIClient`

add_bib_ebookplates.py
Implements [SYS-2020](https://uclalibrary.atlassian.net/browse/SYS-2020)
* `add_bib_ebookplates.py` now uses the updated Alma API client package.
* Instead of using `alma_api_keys.py`, the script now takes an optional parameter `--config_file`, defaulting to `secret_config.toml`.
* All functions have docstrings and type hints.
* Pylance warnings and errors are resolved.
* All previous tests still pass: `python -m unittest tests/test_add_bib_ebookplates.py`
* A new `--limit` parameter is added to limit the number of processed bibs.
To run the script for a small amount of sample data, you can use the sample mappings file in the `tests` directory of this repo with the environment parameter `test` to use two manually selected example bib records: `python add_bib_ebookplates.py …
=> SYS-2020: update add_bib_ebookplates.py for new API client

export_requests_to_caia.py
Implements [SYS-2024](https://uclalibrary.atlassian.net/browse/SYS-2024).
This PR updates the `export_requests_to_caia.py` script:
* Use our Alma API package, latest version (0.2.0)
* Add common config and arguments helpers
* Note: I did not add logging, as this script runs frequently via cron and I want all output to go into a log file I specify in the cron job, not in code.
* Add doc-strings using our current format.
* Fix all pylance errors and warnings.
I opted to keep most program logic in `main()`, because this script does not iterate over data.  Its sole purpose is to run a specific job, though unfortunately, I've found that job ids and even integration profile ids can change, though they usually do not.  For better or worse, rather than hard-coding Alma ids in the script, I use …
=> SYS-2024: Update CAIA request export script with new API package
